### ISSUE TITLE
[Image Submission]: Minemaker / Mocha

### ISSUE THREAD

**Issue by Minemaker0430** [Alphalaneous/ModDevBranding-Images#11]
### Geode username

Minemaker0430

### Image URL

https://cdn.discordapp.com/attachments/730204213791031300/1272726543348797511/Mocha_Watermark_Compact.png?ex=66bc0676&is=66bab4f6&hm=3ed17316910455530b5d2f2cb84f5ffc91207379669931cf0c150ed53ff5b16f&

**Comment by Alphalaneous** [comment]
This image doesn't exist, discord embeds have expiry

**Comment by Alphalaneous** [comment]
doned!

**Comment by Minemaker0430** [comment]
Could you update my username to **ItsMochaTheOtter**? I'm assuming the images are based on display name and I changed mine

**Comment by Alphalaneous** [comment]
This mod is discontinued. It is also no longer listed on geode
