### ISSUE TITLE
[Image Submission]: Cooper, Coop, coopeeo

### ISSUE THREAD

**Issue by coopeeo** [Alphalaneous/ModDevBranding-Images#13]
### Geode username

coopeeo/Cooper/Coop

### Image URL

https://coopeeo.xyz/mod-dev-branding-with-offset.png

### Normal Image (aka without offset)
https://coopeeo.xyz/mod-dev-branding.png

**Comment by Alphalaneous** [comment]
Doned!

**Comment by coopeeo** [comment]
Thanks!
